# Generated by Django 5.1.1 on 2024-09-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.institute'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.institute'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.institute'),
        ),
    ]
